export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_FULFILLED = 'FETCH_ISSUES_FULFILLED';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';
export const SET_ISSUE = 'SET_ISSUE';
